-- 8 Realistic Miami Business Listings for 305business.llc
-- Run this in Supabase Dashboard → SQL Editor after creating schema

INSERT INTO businesses (slug, name, category, description, asking_price, annual_revenue, cash_flow, employee_count, year_established, address, city, state, zip, square_footage, features, equipment_included, reason_for_selling, lease_terms, status, featured, view_count, inquiry_count, seller_name, seller_email) VALUES
('el-palacio-restaurant-lounge', 'El Palacio Restaurant & Lounge', 'restaurant', 'Established Cuban restaurant in the heart of Little Havana. 120 seats, full liquor license, live music venue on weekends. Family-owned for 18 years. Loyal customer base with 4.7 stars on Google.', 485000, 1200000, 185000, 14, 2006, '1528 SW 8th St', 'Miami', 'FL', '33135', 3400, ARRAY['liquor_license','real_estate','established_clients','website'], '["real_estate","equipment","liquor_license","website","social_media"]', 'retirement', 'Property included - owner financing available', 'active', true, 142, 8, 'Roberto Garcia', 'rgarcia@email.com'),

('wynwood-art-gallery-event-space', 'Wynwood Art Gallery & Event Space', 'retail', 'Prime Wynwood location with 20ft street frontage. Gallery hosts 12+ exhibitions annually plus private events (corporate, weddings). Strong Instagram following (45K). Lease through 2028.', 395000, 580000, 125000, 3, 2015, '250 NW 24th St', 'Miami', 'FL', '33127', 2800, ARRAY['established_clients','social_media','website'], '["equipment","social_media","website"]', 'new-venture', '$8,400/mo - NNN, through March 2028, 3% annual increases', 'active', true, 89, 5, 'Cassandra Mills', 'cmills@email.com'),

('brickell-financial-advisory', 'Brickell Financial Advisory', 'service', 'Boutique CPA and financial planning firm serving 180+ clients. Specializes in medical practices and real estate investors. 3 full-time accountants, 2 part-time. Cloud-based workflow (QuickBooks, Xero).', 650000, 890000, 220000, 5, 2012, '801 Brickell Ave, Suite 900', 'Miami', 'FL', '33131', 1800, ARRAY['established_clients','website','trademarks'], '["equipment","website"]', 'relocation', 'Office share agreement - flexible terms', 'active', false, 56, 3, 'David Chen', 'dchen@email.com'),

('coral-gables-dental-practice', 'Coral Gables Dental Practice', 'healthcare', '6-chair general dentistry practice with 2,400 active patients. Digital X-ray, intraoral scanners, CAD/CAM system. Hygiene program generates 40% of revenue. Turnkey for new dentist or DSO acquisition.', 1200000, 1850000, 420000, 8, 2008, '370 Minorca Ave', 'Coral Gables', 'FL', '33134', 3200, ARRAY['real_estate','equipment','established_clients','website'], '["real_estate","equipment","established_clients","website"]', 'retirement', 'Property included in sale', 'active', true, 203, 12, 'Dr. Maria Santos', 'msantos@email.com'),

('south-beach-boutique-hotel', 'South Beach Boutique Hotel', 'hospitality', '18-room Art Deco boutique hotel on Collins Ave. Renovated 2021. 85% annual occupancy, $210 ADR. Breakfast service, rooftop bar (underutilized - growth opportunity). Strong TripAdvisor presence.', 3200000, 1380000, 380000, 12, 1995, '1410 Collins Ave', 'Miami Beach', 'FL', '33139', 8500, ARRAY['real_estate','liquor_license','website','social_media'], '["real_estate","equipment","liquor_license","website","social_media"]', 'new-venture', 'Property included', 'active', true, 178, 9, 'Antonio Ricci', 'aricci@email.com'),

('doral-auto-repair-body-shop', 'Doral Auto Repair & Body Shop', 'automotive', 'Full-service auto repair with 4 bays, 2 body shop stalls, and paint booth. Fleet contracts with 3 local delivery companies. I-CAR certified. Owner manages, doesn''t turn wrenches.', 275000, 680000, 95000, 6, 2011, '7950 NW 53rd St', 'Doral', 'FL', '33166', 4200, ARRAY['equipment','established_clients','website'], '["equipment","established_clients","website"]', 'relocation', '$5,200/mo - industrial zone, through 2026', 'active', false, 67, 4, 'Jorge Mendez', 'jmendez@email.com'),

('north-miami-gym-wellness', 'North Miami Gym & Wellness Center', 'fitness', '8,500 sq ft gym with 340 active memberships ($49-$89/mo). Includes yoga studio, personal training, and nutrition counseling. Brand new equipment (2023). Strong retention (78%).', 425000, 520000, 110000, 7, 2017, '12990 Biscayne Blvd', 'North Miami', 'FL', '33181', 8500, ARRAY['equipment','established_clients','website','social_media'], '["equipment","established_clients","website","social_media"]', 'health', '$12,000/mo - retail space, through 2027', 'active', false, 94, 6, 'Tanya Williams', 'twilliams@email.com'),

('little-havana-bakery-cafe', 'Little Havana Bakery & Café', 'restaurant', 'Corner bakery famous for pastelitos and cafecito. Wholesale accounts with 8 local restaurants and 2 supermarkets. Opens 5 AM, closes 4 PM. Cash business with strong margins.', 195000, 380000, 78000, 4, 2014, '835 SW 16th Ave', 'Miami', 'FL', '33135', 1200, ARRAY['equipment','established_clients','website'], '["equipment","established_clients","website"]', 'retirement', '$3,800/mo - corner retail, through 2026', 'active', false, 112, 7, 'Isabella Rodriguez', 'irodriguez@email.com');
